name: Run Python Tests
run-name: ${{github.actor}} is testing out Github Actions!
on: [push]
jobs:
  Execute-Python-Tests:
    runs-on: ubuntu latest
    steps:
        - name: Checkout and Setup
          uses: actions/checkout@v2
        - name: Setup python
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'
        - name: Install requirmenets
          run: |
            pip install requirments.txt
        - name: Run Tests
        - run: pytest_tests/test_sample.py
        - name: Lists files in Repository
          run: |
            ls ${{ github.workspace }}
        - run: echo "This job status is ${{ job.status }}."
  
